export const LIPA_BARANGAYS = [
  "Adya",
  "Anilao",
  "Anilao-Labac",
  "Antipolo Del Norte",
  "Antipolo Del Sur",
  "Bagong Pook",
  "Balintawak",
  "Banaybanay",
  "Bolbok",
  "Bugtong na Pulo",
  "Bulacnin",
  "Bulaklakan",
  "Calamias",
  "Cumba",
  "Dagatan",
  "Duhatan",
  "Halang",
  "Inosloban",
  "Kayumanggi",
  "Labac",
  "Latag",
  "Lodlod",
  "Lumbang",
  "Malagonlong",
  "Malitlit",
  "Marawoy",
  "Mataas Na Lupa",
  "Munting Pulo",
  "Pagolingin Bata",
  "Pagolingin East",
  "Pagolingin West",
  "Pangao",
  "Pinagkawitan",
  "Pinagtongulan",
  "Plaridel",
  "Poblacion Barangay 1",
  "Poblacion Barangay 2",
  "Poblacion Barangay 3",
  "Poblacion Barangay 4",
  "Poblacion Barangay 5",
  "Poblacion Barangay 6",
  "Poblacion Barangay 7",
  "Poblacion Barangay 8",
  "Poblacion Barangay 9",
  "Poblacion Barangay 9-A",
  "Poblacion Barangay 10",
  "Poblacion Barangay 11",
  "Poblacion Barangay 12",
  "Pusil",
  "Quezon",
  "Rizal",
  "Sabang",
  "Sampaguita",
  "San Benito",
  "San Carlos",
  "San Celestino",
  "San Francisco",
  "San Guillermo",
  "San Isidro",
  "San Jose",
  "San Lucas",
  "San Salvador",
  "San Sebastian",
  "Santo Nio",
  "Santo Toribio",
  "Sapang",
  "Sico",
  "Talisay",
  "Tambo",
  "Tangob",
  "Tanguay",
  "Tibig",
  "Tipacan"
].sort();
